services:
  - type: web
    name: appliance-price-tracker-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node test-server.js
    envVars:
      - key: NODE_ENV
        value: production 